import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ClientLayout from "./_components/ClientLayout";

export const metadata: Metadata = {
  title: "Nipun Yasas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
